import {
  Tag,
  Utensils,
  Car,
  Home,
  Film,
  Tv,
  Briefcase,
  Globe,
  Heart,
  Shield,
  BookOpen,
  Scissors,
  Coffee,
  ShoppingBag,
  ShoppingCart,
  Zap,
  Gift,
  Wrench,
  PawPrint,
  Dumbbell,
  Laptop,
  Smartphone,
  CreditCard,
  Wallet,
  Coins,
  Banknote,
  TrendingUp,
  Plane,
  Music,
  Gamepad2,
  GraduationCap,
  Sparkles,
  Pizza,
  Beer,
  Stethoscope,
  Smile,
  DollarSign,
  Bitcoin,
  Package,
} from "lucide-react";

// Canonical icons displayed in icon pickers
export const AVAILABLE_ICONS = [
  { name: "tag", icon: Tag },
  { name: "utensils", icon: Utensils },
  { name: "shopping-bag", icon: ShoppingBag },
  { name: "shopping-cart", icon: ShoppingCart },
  { name: "coffee", icon: Coffee },
  { name: "pizza", icon: Pizza },
  { name: "beer", icon: Beer },
  { name: "car", icon: Car },
  { name: "plane", icon: Plane },
  { name: "home", icon: Home },
  { name: "zap", icon: Zap },
  { name: "film", icon: Film },
  { name: "tv", icon: Tv },
  { name: "music", icon: Music },
  { name: "gamepad", icon: Gamepad2 },
  { name: "briefcase", icon: Briefcase },
  { name: "laptop", icon: Laptop },
  { name: "smartphone", icon: Smartphone },
  { name: "book", icon: BookOpen },
  { name: "graduation-cap", icon: GraduationCap },
  { name: "heart", icon: Heart },
  { name: "stethoscope", icon: Stethoscope },
  { name: "dumbbell", icon: Dumbbell },
  { name: "sparkles", icon: Sparkles },
  { name: "scissors", icon: Scissors },
  { name: "paw-print", icon: PawPrint },
  { name: "gift", icon: Gift },
  { name: "package", icon: Package },
  { name: "wrench", icon: Wrench },
  { name: "shield", icon: Shield },
  { name: "wallet", icon: Wallet },
  { name: "credit-card", icon: CreditCard },
  { name: "banknote", icon: Banknote },
  { name: "coins", icon: Coins },
  { name: "dollar-sign", icon: DollarSign },
  { name: "trending-up", icon: TrendingUp },
  { name: "bitcoin", icon: Bitcoin },
  { name: "globe", icon: Globe },
  { name: "smile", icon: Smile },
];

// Lookup map including aliases and fallback
export const ICON_MAP = {
  ...Object.fromEntries(AVAILABLE_ICONS.map(({ name, icon }) => [name, icon])),
  // Aliases for common database strings
  shopping: ShoppingBag,
  cart: ShoppingCart,
  utilities: Zap,
  pets: PawPrint,
  pet: PawPrint,
  gym: Dumbbell,
  fitness: Dumbbell,
  education: GraduationCap,
  health: Heart,
  healthcare: Stethoscope,
  travel: Plane,
  tech: Laptop,
  software: Laptop,
  salary: Banknote,
  investment: TrendingUp,
  investments: TrendingUp,
  crypto: Bitcoin,
  food: Utensils,
  restaurant: Utensils,
  restaurants: Utensils,
  transport: Car,
  taxi: Car,
  entertainment: Film,
  services: Wrench,
  service: Wrench,
  gifts: Gift,
  subscriptions: Tv,
  subscription: Tv,
  housing: Home,
  rent: Home,
};

// Returns a component for a given icon name, falls back to Tag
export const getIconComponent = (iconName) => {
  if (!iconName) return Tag;
  const normalized = String(iconName).toLowerCase().trim();
  return ICON_MAP[normalized] ?? Tag;
};
